name: WireGuard Verbindungstest

on:
  workflow_dispatch:

jobs:
  test-vpn:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: WireGuard installieren
        run: |
          sudo apt update
          sudo apt install -y wireguard iproute2 curl

      - name: WireGuard Tunnel testen
        run: |
          # Temporäre Konfigurationsdatei mit .conf erstellen
          WG_CONF=$(mktemp wg0-XXXX.conf)
          echo "[Interface]
          PrivateKey = ${{ secrets.WG_PRIVATE_KEY }}
          Address = 10.0.0.2/24
          DNS = 1.1.1.1

          [Peer]
          PublicKey = ${{ secrets.WG_SERVER_PUBLIC_KEY }}
          Endpoint = ${{ secrets.WG_ENDPOINT }}
          AllowedIPs = ${{ secrets.WG_ALLOWED_IPS }}" > $WG_CONF

          # Tunnel starten
          sudo wg-quick up $WG_CONF

          # Verbindung prüfen
          echo "Meine öffentliche IP über WireGuard:"
          curl -s https://ifconfig.me

          # Tunnel stoppen
          sudo wg-quick down $WG_CONF

          # Temporäre Datei löschen
          rm -f $WG_CONF
